use_pca_box: False
use_tracking: False

voxel_grid_size: 0.2
roi_max_x: 70
roi_max_y : 30
roi_max_z : 1

roi_min_x: -30
roi_min_y: -30
roi_min_z: -2.5

neighbors : 50
standard_deviation : 1

ground_threshold: 0.4

cluster_threshold: 0.6
cluster_max_size: 5000
cluster_min_size: 10

displacement_threshold: 1.0
iou_threshold: 1.0

# use_pca_box: False
# use_tracking: False

# voxel_grid_size: 0.2
# roi_max_x: 70
# roi_max_y : 30
# roi_max_z : 10

# roi_min_x: -30
# roi_min_y: -30
# roi_min_z: -2.5

# ground_threshold: 0.2

# cluster_threshold: 0.6
# cluster_max_size: 5000
# cluster_min_size: 10

# displacement_threshold: 1.0
# iou_threshold: 1.0

